irCandi/urls.py
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import admin
from django.urls import path
import main.urls as main 
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('main/', include(main)),
    # url(r'^main/', include(main, namespace='main')),
    url(r'^main/', include(('main.urls', 'main'), namespace='main')),
    path('', RedirectView.as_view(
        url='/main/', permanent=True
    )),
]

main/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, show_aspect

urlpatterns = [
     path("", index, name='index'),
     url(r'^result/(?P<id>\w{0,50})/$', show_aspect, name='show_aspect')
     # path("result/(?P<id>\w{0,50})",show_aspect, name='result')
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Candi(models.Model):
	id_file = models.IntegerField(default=0)
	nama = models.CharField(max_length=30)

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .aspect import SentimentWordNet, set_review, aspect_evaluation

# ASPECTS 
building = []
ambience = []
price_service = []
sorrounding = []
merchant = []
# Create your views here.
response = {
        "building" : {
            "positive": 0.0,
            "negative": 0.0,
            "neutral": 0.0
        }, #positive, negative, neutral
        "ambience" : {
            "positive": 0.0,
            "negative": 0.0,
            "neutral": 0.0
        },
        "price_service" : {
            "positive": 0.0,
            "negative": 0.0,
            "neutral": 0.0
        },
        "surrounding" : {
            "positive": 0.0,
            "negative": 0.0,
            "neutral": 0.0
        },
        "merchant" : {
            "positive": 0.0,
            "negative": 0.0,
            "neutral": 0.0
        }
}

def index(request):
    with open('main/txt/cluster.txt', encoding="utf8") as noun:
        for line in noun:
            word = line.split()
            print(word)
            if (len(word) == 1):
                continue
            elif (word[1] == "1"):
                building.append(word[0])
            elif (word[1] == "2"):
                ambience.append(word[0])
            elif (word[1] == "3"):
                price_service.append(word[0])
            elif (word[1] == "4"):
                sorrounding.append(word[0])
            elif (word[1] == "5"):
                merchant.append(word[0])
            else :
                continue
    return render(request, 'index.html', response)


def show_aspect(request, id):
    # reset_all()
    # get txt objects from model
    sentencez = set_review("main/txt/" + id + ".txt") # file reviewnya
    dictionary = SentimentWordNet("main/txt/swnALL.txt") # file SWN nya
    # get clusternya

    score = aspect_evaluation(sentencez, building, ambience, price_service, sorrounding, merchant, dictionary)
    print(score)
    for i in score.keys():
        print(i)
        response[i]["positive"] = get_score(score, 0, i)
        response[i]["negative"] = get_score(score, 1, i)
        response[i]["neutral"] = get_score(score, 2, i)

    return render(request, 'result.html', response)


def get_score(score, attitude, i):
    print(score['building'])
    print(score[i])
    total = score[i][0] + score[i][1] + score[i][2]
    return score[i][attitude] / float(total)

def result(request):
    return render(request, 'result.html', response)

main/templates/index.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <title>Aspect Sentiment for Indonesian Temple</title>

</head>
<body>
    <header class="site-header">
        <div class="top-header-bar">
            <div class="container">
                <div class="row flex-wrap justify-content-center justify-content-lg-between align-items-lg-center">
                    <div class="col-12 col-lg-8 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                        <div class="header-bar-email">
                            Kelompok Tyrannosaurus
                        </div><!-- .header-bar-email -->

                        <div class="header-bar-text">
                            <i><b>Aspect Based Sentiment Analysis</b></i> Candi di Indonesia
                        </div><!-- .header-bar-text -->
                    </div><!-- .col -->

                    <div class="col-12 col-lg-4 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                        <div class="donate-btn">
                            <a href="#"><b>Ezza & Thoriq</b></a>
                        </div><!-- .donate-btn -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .top-header-bar -->

    </header><!-- .site-header -->

    <div class="container content">
        <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Borobudur Temple</h3>
                        <p class="card-text">This famous Buddhist temple, dating from the 8th and 9th centuries, is located in central Java. It was built in three tiers: a pyramidal base with five concentric square terraces, the trunk of a cone with three circular platforms and, at the top, a monumental stupa. The walls and balustrades are decorated with fine low reliefs, covering a total surface area of 2,500 m2. Around the circular platforms are 72 openwork stupas, each containing a statue of the Buddha. The monument was restored with UNESCO's help in the 1970s.</p>
                        <!-- <a href="/main/result/" class="btn">What tourists think about?</a> -->
                        <a href="{% url 'main:show_aspect' 1 %}" class="btn">What tourists think about?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
</body>
</html>

main/templates/result.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/result.css' %}" type="text/css">
    <title>Aspect Sentiment for Indonesian Temple</title>

</head>
<body>
    <header class="site-header">
        <div class="top-header-bar">
            <div class="container">
                <div class="row flex-wrap justify-content-center justify-content-lg-between align-items-lg-center">
                    <div class="col-12 col-lg-8 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                        <div class="header-bar-email">
                            Kelompok Tyrannosaurus
                        </div><!-- .header-bar-email -->

                        <div class="header-bar-text">
                            <i><b>Aspect Based Sentiment Analysis</b></i> Candi di Indonesia
                        </div><!-- .header-bar-text -->
                    </div><!-- .col -->

                    <div class="col-12 col-lg-4 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                        <div class="donate-btn">
                            <a href="#"><b>Ezza & Thoriq</b></a>
                        </div><!-- .donate-btn -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .top-header-bar -->

    </header><!-- .site-header -->

    <div class="container content">
        <div class="row grafik">
            <div class="col-xs-8 col-md-8 col-lg-8">
                <canvas id="bar-chart-grouped"></canvas>
            </div>
            <div class="col-xs-4 col-md-4 col-lg-4 explanation">
                <a href="/main">Back To Home</a>
                <h3>Explanation</h3>
                <p><b>Aspect Building:</b> Merupakan aspek yang menjelaskan tentang bangunan Candi Borobudur</p>
                <p><b>Aspect Ambience:</b> Merupakan aspek yang menjelaskan tentang suasana, pemandangan dan perasaan yang dirasakan turis</p>
                <p><b>Aspect Price & Service:</b> Merupakan aspek yang menjelaskan tentang harga tiket, peraturan dan tour guide yang berada di sekitar Candi Borobudur</p>
                <p><b>Aspect Surrounding:</b> Merupakan aspek yang menjelaskan tentang daerah sekitar candi yang meliputi atraksi dan acara sekitar candi</p>
                <p><b>Aspect Merchant:</b> Merupakan aspek yang menjelaskan tentang penjual souvenir sekitar candi</p>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script type="text/javascript">
        var stackedBar = new Chart(document.getElementById("bar-chart-grouped"), {
                            type: 'bar',
                            data: {
                                  labels: ["Building", "Ambience", "Price & Service", "Surround Area", "Merchant"],
                                  datasets: [
                                    {
                                      label: "Positive",
                                      backgroundColor: "#d8f135",
                                      data: [{{building.positive}},
                                      {{ambience.positive}},
                                      {{price_service.positive}}, 
                                      {{surrounding.positive}},
                                      {{merchant.positive}}]
                                    }, {
                                      label: "Negative",
                                      backgroundColor: "#f26a35",
                                      data: [{{building.negative}},
                                      {{ambience.negative}},
                                      {{price_service.negative}}, 
                                      {{surrounding.negative}},
                                      {{merchant.negative}}]
                                    },
                                    {
                                      label: "Neutral",
                                      backgroundColor: "#f0de34",
                                      data: [{{building.neutral}},
                                      {{ambience.neutral}},
                                      {{price_service.neutral}}, 
                                      {{surrounding.neutral}},
                                      {{merchant.neutral}}]
                                    }
                                  ]
                                },
                            options: {
                                scales: {
                                    xAxes: [{
                                        stacked: true
                                    }],
                                    yAxes: [{
                                        stacked: true
                                    }]
                                }
                            }
                        });
    </script>
</body>
</html>